name: C++ CI with CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Create build environment
        shell: bash
        run: cmake -E make_directory $GITHUB_WORKSPACE/build
      - name: Configure CMake
        shell: bash
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build
      - name: Build
        shell: bash
        run: cmake --build $GITHUB_WORKSPACE/build
      - name: Test
        shell: bash
        run: ctest -VV --test-dir $GITHUB_WORKSPACE/build
